# Generated by Django 4.2.11 on 2025-11-20 16:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreneauTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('heure_debut', models.TimeField()),
                ('heure_fin', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Créneaux de travail',
                'ordering': ['heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Départements',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('type_equipement', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('marque', models.CharField(blank=True, max_length=100, null=True)),
                ('modele', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Équipements',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Grades',
                'ordering': ['intitule'],
            },
        ),
        migrations.CreateModel(
            name='OutilTravail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('url_acces', models.URLField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Outils de travail',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('email_professionnel', models.EmailField(max_length=254, unique=True)),
                ('email_personnel', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone_professionnel', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_personnel', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_professionnel', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('date_embauche', models.DateField(blank=True, null=True)),
                ('date_sortie', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('CONSULTANT', 'Consultant')], default='CDI', max_length=50)),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin'), ('AUTRE', 'Autre')], max_length=10, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grade')),
            ],
            options={
                'verbose_name_plural': 'Salariés',
                'ordering': ['prenom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Societe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('ville', models.CharField(blank=True, max_length=100, null=True)),
                ('code_postal', models.CharField(blank=True, max_length=10, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Sociétés',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeApplicationAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': "Types d'application d'accès",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types_acces', to='api.societe')),
            ],
            options={
                'verbose_name_plural': "Types d'accès",
                'ordering': ['nom'],
                'unique_together': {('nom', 'societe')},
            },
        ),
        migrations.CreateModel(
            name='TravauxExceptionnels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_travail', models.DateField()),
                ('heures', models.FloatField()),
                ('type_travail', models.CharField(max_length=50)),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('COMPENSATED', 'Compensé')], default='PENDING', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travaux_exceptionnels', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Travaux exceptionnels',
                'ordering': ['-date_travail'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('societe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.societe')),
            ],
            options={
                'verbose_name_plural': 'Services',
                'ordering': ['nom'],
                'unique_together': {('nom', 'societe')},
            },
        ),
        migrations.AddField(
            model_name='salarie',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service'),
        ),
        migrations.AddField(
            model_name='salarie',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='api.societe'),
        ),
        migrations.CreateModel(
            name='HoraireSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_horaire', models.CharField(choices=[('TEMPS_PLEIN', 'Temps plein'), ('TEMPS_PARTIEL', 'Temps partiel'), ('FLEXIBILITE', 'Flexibilité')], default='TEMPS_PLEIN', max_length=50)),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('creneaux', models.ManyToManyField(blank=True, to='api.creneautravail')),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horaires', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Horaires des salariés',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_modification', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CHANGEMENT_POSTE', 'Changement de poste')], max_length=50)),
                ('description', models.TextField()),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='api.salarie')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Historique des salariés',
                'ordering': ['-date_modification'],
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='societe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.societe'),
        ),
        migrations.CreateModel(
            name='FichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('competences_requises', models.TextField(blank=True, null=True)),
                ('responsabilites', models.TextField(blank=True, null=True)),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.grade')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.service')),
            ],
            options={
                'verbose_name_plural': 'Fiches de poste',
                'ordering': ['titre'],
            },
        ),
        migrations.CreateModel(
            name='FicheParametresUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_couleur', models.CharField(default='light', max_length=50)),
                ('langue', models.CharField(default='fr', max_length=10)),
                ('notifications_activees', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('salarié', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Fiches de paramètres utilisateur',
            },
        ),
        migrations.CreateModel(
            name='EquipementInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('etat', models.CharField(choices=[('NEUF', 'Neuf'), ('BON', 'Bon état'), ('USURE', 'Usure'), ('ENREPARATION', 'En réparation'), ('HORS_SERVICE', 'Hors service')], default='BON', max_length=50)),
                ('date_attribution', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.equipement')),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': "Instances d'équipement",
                'ordering': ['-date_attribution'],
            },
        ),
        migrations.CreateModel(
            name='DocumentSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat'), ('FICHE_POSTE', 'Fiche de poste'), ('ATTESTATION', 'Attestation'), ('AUTRE', 'Autre')], max_length=50)),
                ('nom', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Documents des salariés',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('statut', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Approuvé'), ('REJECTED', 'Rejeté'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=50)),
                ('motif', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_decision', models.DateTimeField(blank=True, null=True)),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-date_demande'],
            },
        ),
        migrations.CreateModel(
            name='AmeliorationProposee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priorite', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('statut_projet', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('EVALUEE', 'Évaluée'), ('APPROUVEE', 'Approuvée'), ('REJETEE', 'Rejetée'), ('IMPLEMENTEE', 'Implémentée')], default='PROPOSEE', max_length=50)),
                ('date_proposition', models.DateTimeField(auto_now_add=True)),
                ('date_implementation', models.DateTimeField(blank=True, null=True)),
                ('fiche_poste', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ameliorations', to='api.ficheposte')),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ameliorations_proposees', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Améliorations proposées',
                'ordering': ['-priorite', '-date_proposition'],
            },
        ),
        migrations.CreateModel(
            name='SoldeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('jours_acquis', models.FloatField(default=25)),
                ('jours_utilises', models.FloatField(default=0)),
                ('jours_restants', models.FloatField(default=25)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soldes_conge', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Soldes de congé',
                'ordering': ['-annee'],
                'unique_together': {('salarié', 'annee')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='salarie',
            unique_together={('email_professionnel',)},
        ),
        migrations.CreateModel(
            name='OutilFichePoste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('fiche_poste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outils', to='api.ficheposte')),
                ('outil_travail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outiltravail')),
                ('type_acces_requis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeacces')),
            ],
            options={
                'verbose_name_plural': 'Outils des fiches de poste',
                'ordering': ['fiche_poste'],
                'unique_together': {('fiche_poste', 'outil_travail')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('intitule', 'societe')},
        ),
        migrations.CreateModel(
            name='AccesSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('outil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.outiltravail')),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_outils', to='api.salarie')),
                ('type_acces', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.typeacces')),
            ],
            options={
                'verbose_name_plural': 'Accès des salariés',
                'ordering': ['-date_debut'],
                'unique_together': {('salarié', 'outil')},
            },
        ),
        migrations.CreateModel(
            name='AccesApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(auto_now_add=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.typeapplicationacces')),
                ('salarié', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acces_applications', to='api.salarie')),
            ],
            options={
                'verbose_name_plural': 'Accès aux applications',
                'ordering': ['-date_debut'],
                'unique_together': {('salarié', 'application')},
            },
        ),
    ]
